services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FLUTTER_ENV: production  # Sett til 'production' for bygging
    ports:
      - "80:80"
    environment:
      - FLUTTER_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - wedding_network

networks:
  wedding_network:
    driver: bridge
