# render.yaml
services:
  - type: web
    name: wedding2025-frontend
    env: static
    buildCommand: flutter build web --release
    staticPublishPath: ./build/web
    envVars:
      - key: FLUTTER_VERSION
        value: 3.27.1
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html